# Generated by Django 4.1.2 on 2022-10-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRootUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, null=True)),
                ('mother_surname', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('date_of_marry', models.DateField(default=None, null=True)),
                ('unique_root', models.UUIDField(default=uuid.UUID('6babf329-546f-11ed-b821-2c4d54929b0f'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информация о корне дерева',
                'verbose_name_plural': 'Информация о корне дерева',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('mother_surname', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('date_of_marry', models.DateField(default=None, null=True)),
                ('date_of_death', models.DateField(default=None, null=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001E45F131C60>/male')),
                ('is_published', models.BooleanField(default=False)),
                ('unique_male', models.UUIDField(default=uuid.UUID('6bac685e-546f-11ed-a172-2c4d54929b0f'))),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.mainrootuser')),
            ],
            options={
                'verbose_name': 'Информация о корне дерева',
                'verbose_name_plural': 'Информация о корне дерева',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FemaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('mother_surname', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('date_of_marry', models.DateField(default=None, null=True)),
                ('date_of_death', models.DateField(default=None, null=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001E45F131C60>/female')),
                ('is_published', models.BooleanField(default=False)),
                ('unique_female', models.UUIDField(default=uuid.UUID('6bac414a-546f-11ed-8a01-2c4d54929b0f'))),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.mainrootuser')),
            ],
            options={
                'verbose_name': 'Информация о листьях дерева',
                'verbose_name_plural': 'Информация о листьях дерева',
                'ordering': ['id'],
            },
        ),
    ]
