# Generated by Django 4.1.2 on 2022-12-11 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainRootUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=255, null=True)),
                ("mother_surname", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(default=None, null=True)),
                ("place_of_birth", models.CharField(max_length=255, null=True)),
                ("date_of_marry", models.DateField(default=None, null=True)),
                ("is_dead", models.BooleanField(default=False)),
                ("date_of_death", models.DateField(default=None, null=True)),
                ("years", models.CharField(default=None, max_length=255, null=True)),
                (
                    "unique_root",
                    models.UUIDField(
                        default=uuid.UUID("a92d338e-794c-11ed-a069-2c3b706d7921")
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корінь дерева",
                "verbose_name_plural": "Корінь дерева",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("surname", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("mother_surname", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(default=None, null=True)),
                ("place_of_birth", models.CharField(max_length=255, null=True)),
                ("date_of_marry", models.DateField(default=None, null=True)),
                ("date_of_death", models.DateField(default=None, null=True)),
                (
                    "document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001C9A8A4D4D0>/male",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "unique_male",
                    models.UUIDField(
                        default=uuid.UUID("a92d5af8-794c-11ed-a87d-2c3b706d7921")
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tree.mainrootuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Інформація по чоловічій лінії",
                "verbose_name_plural": "Інформація по чоловічій лінії",
            },
        ),
        migrations.CreateModel(
            name="MainRootUserWife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("surname", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("mother_surname", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(default=None, null=True)),
                ("place_of_birth", models.CharField(max_length=255, null=True)),
                ("date_of_marry", models.DateField(default=None, null=True)),
                ("is_dead", models.BooleanField(default=False)),
                ("date_of_death", models.DateField(default=None, null=True)),
                ("years", models.CharField(default=None, max_length=255, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("a92d338f-794c-11ed-8151-2c3b706d7921"),
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "spouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tree.mainrootuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дружина",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MainRootUserSpouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("surname", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("mother_surname", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(default=None, null=True)),
                ("place_of_birth", models.CharField(max_length=255, null=True)),
                ("date_of_marry", models.DateField(default=None, null=True)),
                ("is_dead", models.BooleanField(default=False)),
                ("date_of_death", models.DateField(default=None, null=True)),
                ("years", models.CharField(default=None, max_length=255, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("a92d3390-794c-11ed-a171-2c3b706d7921"),
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wife",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tree.mainrootuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чоловік",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FemaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("surname", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("mother_surname", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(default=None, null=True)),
                ("place_of_birth", models.CharField(max_length=255, null=True)),
                ("date_of_marry", models.DateField(default=None, null=True)),
                ("date_of_death", models.DateField(default=None, null=True)),
                (
                    "document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001C9A8A4D4D0>/female",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "unique_female",
                    models.UUIDField(
                        default=uuid.UUID("a92d5af7-794c-11ed-9518-2c3b706d7921")
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tree.mainrootuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Інформація по жіночій лінії",
                "verbose_name_plural": "Інформація по жіночій лінії",
            },
        ),
    ]
