# Generated by Django 4.1.2 on 2022-10-26 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='femaleline',
            options={'verbose_name': 'Інформація по жіночій лінії', 'verbose_name_plural': 'Інформація по жіночій лінії'},
        ),
        migrations.AlterModelOptions(
            name='mainrootuser',
            options={'ordering': ['id'], 'verbose_name': 'Корінь дерева', 'verbose_name_plural': 'Корінь дерева'},
        ),
        migrations.AlterModelOptions(
            name='maleline',
            options={'verbose_name': 'Інформація по чоловічій лінії', 'verbose_name_plural': 'Інформація по чоловічій лінії'},
        ),
        migrations.AddField(
            model_name='mainrootuser',
            name='date_of_death',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainrootuser',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainrootuser',
            name='years',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x00000239AE83FF40>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('d1267e2b-551a-11ed-ba14-2c4d54929b0f')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('d1265703-551a-11ed-82f4-2c4d54929b0f')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x00000239AE83FF40>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('d126cc39-551a-11ed-bc1a-2c4d54929b0f')),
        ),
    ]
