# Generated by Django 4.1.2 on 2022-12-11 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0002_femaleline_prev_ancestor_femaleline_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="femaleline",
            name="unique_female",
            field=models.UUIDField(
                default=uuid.UUID("e861ac63-794e-11ed-ad2a-2c3b706d7921")
            ),
        ),
        migrations.AlterField(
            model_name="femalelinechild",
            name="unique_female",
            field=models.UUIDField(
                default=uuid.UUID("e861d336-794e-11ed-9dd7-2c3b706d7921")
            ),
        ),
        migrations.AlterField(
            model_name="mainrootuser",
            name="unique_root",
            field=models.UUIDField(
                default=uuid.UUID("e8618486-794e-11ed-8b30-2c3b706d7921")
            ),
        ),
        migrations.AlterField(
            model_name="mainrootuserspouse",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("e861ac62-794e-11ed-84f5-2c3b706d7921"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mainrootuserwife",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("e8618487-794e-11ed-b675-2c3b706d7921"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="maleline",
            name="unique_male",
            field=models.UUIDField(
                default=uuid.UUID("e861ac64-794e-11ed-b80e-2c3b706d7921")
            ),
        ),
        migrations.AlterField(
            model_name="malelinechild",
            name="unique_male_child",
            field=models.UUIDField(
                default=uuid.UUID("e861d337-794e-11ed-902f-2c3b706d7921")
            ),
        ),
    ]
