# Generated by Django 4.1.2 on 2022-10-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0003_alter_femaleline_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainrootuserwife',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mainrootuserwife',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x00000270DE7F4190>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('d698e4c0-560d-11ed-aaae-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('d6984906-560d-11ed-b23b-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('d69896a4-560d-11ed-925c-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x00000270DE7F4190>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('d69932f3-560d-11ed-a34c-3ca0670b2ec7')),
        ),
    ]
