# Generated by Django 4.1.2 on 2022-10-27 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_alter_femaleline_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000028CDD2F4190>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('79957f2a-5610-11ed-a48e-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('799530fe-5610-11ed-9723-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('7995580c-5610-11ed-bbe2-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000028CDD2F4190>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('79964281-5610-11ed-b063-3ca0670b2ec7')),
        ),
    ]
