# Generated by Django 4.1.2 on 2022-10-27 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_alter_femaleline_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainrootuserwife',
            options={'ordering': ['id'], 'verbose_name': 'Дружина'},
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001DB4E454190>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('ff55ba49-5610-11ed-8f0b-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('ff551dfe-5610-11ed-a2bd-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='spouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.mainrootuser'),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('ff554531-5610-11ed-8293-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001DB4E454190>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('ff560878-5610-11ed-b7d2-3ca0670b2ec7')),
        ),
    ]
