# Generated by Django 4.1.2 on 2022-10-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0008_alter_mainrootuserwife_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000002099A934190>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('1b99ccf2-5611-11ed-a16f-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('1b9930cb-5611-11ed-93f0-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('1b997ece-5611-11ed-8eb3-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000002099A934190>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('1b9a1b54-5611-11ed-8dca-3ca0670b2ec7')),
        ),
    ]
