# Generated by Django 4.1.2 on 2022-10-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0009_alter_femaleline_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001BAF6EDF550>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('763e0a7b-5612-11ed-8af6-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('763d473f-5612-11ed-9a7c-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('763d9569-5612-11ed-a192-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x000001BAF6EDF550>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('763e58b1-5612-11ed-85f5-3ca0670b2ec7')),
        ),
        migrations.CreateModel(
            name='MainRootUserSpouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('mother_surname', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('date_of_marry', models.DateField(default=None, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(default=None, null=True)),
                ('years', models.CharField(default=None, max_length=255, null=True)),
                ('unique_root', models.UUIDField(default=uuid.UUID('763dbc6b-5612-11ed-a70f-3ca0670b2ec7'))),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.mainrootuser')),
            ],
            options={
                'verbose_name': 'Чоловік',
                'ordering': ['id'],
            },
        ),
    ]
