# Generated by Django 4.1.2 on 2022-10-27 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_alter_femaleline_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainrootuserwife',
            name='unique_root',
        ),
        migrations.AddField(
            model_name='mainrootuserwife',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('87a8f7d1-563c-11ed-adfb-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000023F0B50F550>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('87a9bb5f-563c-11ed-b430-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('87a8a9af-563c-11ed-974b-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserspouse',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('87a96d2a-563c-11ed-9828-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000023F0B50F550>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('87aa0953-563c-11ed-a4ef-3ca0670b2ec7')),
        ),
    ]
