# Generated by Django 4.1.2 on 2022-10-27 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_remove_mainrootuserspouse_unique_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000013AF3ACF520>/female'),
        ),
        migrations.AlterField(
            model_name='femaleline',
            name='unique_female',
            field=models.UUIDField(default=uuid.UUID('a6a67695-563e-11ed-9467-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuser',
            name='unique_root',
            field=models.UUIDField(default=uuid.UUID('a6a60085-563e-11ed-8914-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserspouse',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6a64e76-563e-11ed-bb91-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='mainrootuserwife',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6a6279c-563e-11ed-9d92-3ca0670b2ec7')),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='tree/<django.db.models.query_utils.DeferredAttribute object at 0x0000013AF3ACF520>/male'),
        ),
        migrations.AlterField(
            model_name='maleline',
            name='unique_male',
            field=models.UUIDField(default=uuid.UUID('a6a6c4e8-563e-11ed-b734-3ca0670b2ec7')),
        ),
    ]
