# Generated by Django 4.1.2 on 2022-12-11 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("cbb42e31-794e-11ed-a981-2c3b706d7921")
            ),
        ),
    ]
