# Generated by Django 4.1.2 on 2022-12-11 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_useraccount_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("e860c05a-794e-11ed-b076-2c3b706d7921")
            ),
        ),
    ]
