# Generated by Django 4.1.2 on 2022-10-21 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('67e8f399-5148-11ed-ab1d-3ca0670bcd37')),
        ),
    ]
