# Generated by Django 4.1.2 on 2022-10-21 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('27de036e-514b-11ed-a411-3ca0670bcd37')),
        ),
    ]
