# Generated by Django 4.1.2 on 2022-10-21 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e6f2816f-514c-11ed-8ef7-3ca0670bcd37')),
        ),
    ]
