# Generated by Django 4.1.2 on 2022-10-21 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ca9b85a1-514d-11ed-9455-3ca0670bcd37')),
        ),
    ]
