# Generated by Django 4.1.2 on 2022-10-22 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_useraccount_options_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9d7a166d-5212-11ed-9135-3ca0670bcd37')),
        ),
    ]
