# Generated by Django 4.1.2 on 2022-10-22 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4d690509-5213-11ed-8db9-3ca0670bcd37')),
        ),
    ]
