# Generated by Django 4.1.2 on 2022-10-22 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9618ffc8-521a-11ed-8c7c-3ca0670bcd37')),
        ),
    ]
