# Generated by Django 4.1.2 on 2022-10-22 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e31d054d-521a-11ed-afa3-3ca0670bcd37')),
        ),
    ]
