# Generated by Django 4.1.2 on 2022-10-22 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4589a90d-521b-11ed-b266-3ca0670bcd37')),
        ),
    ]
