# Generated by Django 4.1.2 on 2022-10-22 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6fee3f93-5220-11ed-ac53-3ca0670bcd37')),
        ),
    ]
