# Generated by Django 4.1.2 on 2022-10-25 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c5e8f586-545c-11ed-8769-2c4d54929b0f')),
        ),
    ]
