# Generated by Django 4.1.2 on 2022-10-25 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7dc79269-545d-11ed-9059-2c4d54929b0f')),
        ),
    ]
