# Generated by Django 4.1.2 on 2022-10-25 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1a7c9eb3-5466-11ed-a89b-2c4d54929b0f')),
        ),
    ]
