# Generated by Django 4.1.2 on 2022-10-25 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e5b356ae-546a-11ed-8853-2c4d54929b0f')),
        ),
    ]
