# Generated by Django 4.1.2 on 2022-10-25 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6ba93429-546f-11ed-bac7-2c4d54929b0f')),
        ),
    ]
