# Generated by Django 4.1.2 on 2022-10-27 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7990c40e-5610-11ed-a574-3ca0670b2ec7')),
        ),
    ]
