# Generated by Django 4.1.2 on 2022-10-27 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b0b441ed-5610-11ed-8a28-3ca0670b2ec7')),
        ),
    ]
