# Generated by Django 4.1.2 on 2022-10-27 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ff51c2b1-5610-11ed-9e45-3ca0670b2ec7')),
        ),
    ]
