# Generated by Django 4.1.2 on 2022-10-27 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1b95ae22-5611-11ed-9232-3ca0670b2ec7')),
        ),
    ]
