# Generated by Django 4.1.2 on 2022-10-27 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sex',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('76399dc6-5612-11ed-9f38-3ca0670b2ec7')),
        ),
    ]
