# Generated by Django 4.1.2 on 2022-10-27 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a69c694e-563e-11ed-98d0-3ca0670b2ec7')),
        ),
    ]
