version: '3'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ".env.docker"
    networks:
      - tree-network
    command: -p 5433

  web:
    build: .
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - tree-network

volumes:
  postgres_data:

networks:
  tree-network:
    driver: bridge
