# Generated by Django 4.1.2 on 2022-12-11 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(default=None, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="A:\\FamilyTree\\Tree\\GenealogyBoutiqueTreeBack\\backend\\media/userprofile/photos/default.jpg",
                        null=True,
                        upload_to="photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001C9A8A4D4D0>/",
                    ),
                ),
                ("telegram", models.URLField(default=None, null=True)),
                ("facebook", models.URLField(default=None, null=True)),
                ("whatsapp", models.URLField(default=None, null=True)),
                ("twitter", models.URLField(default=None, null=True)),
                ("linkedin", models.URLField(default=None, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профіль користувачів",
                "verbose_name_plural": "Профіль користувачів",
                "ordering": ["id"],
            },
        ),
    ]
