# Generated by Django 4.1.2 on 2022-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="A:\\FamilyTree\\Tree\\GenealogyBoutiqueTreeBack\\backend\\media/userprofile/photos/default.jpg",
                null=True,
                upload_to="photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002113E504D90>/",
            ),
        ),
    ]
