# Generated by Django 4.1.2 on 2022-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.URLField(default=None),
        ),
    ]
