# Generated by Django 4.1.2 on 2022-10-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
