# Generated by Django 4.1.2 on 2022-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_userprofile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='userprofile/static/photos/'),
        ),
    ]
