# Generated by Django 4.1.2 on 2022-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль пользователя'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='D:\\Metrics\\GenealogyBoutiqueTree\\backend\\media/userprofile/photos/default.jpg', upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002BF3AA1B580>/'),
        ),
    ]
