# Generated by Django 4.1.2 on 2022-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='D:\\Metrics\\GenealogyBoutiqueTree\\backend\\media/userprofile/photos/default.jpg', upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000023D83D0B580>/'),
        ),
    ]
