# Generated by Django 4.1.2 on 2022-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'Профіль користувачів', 'verbose_name_plural': 'Профіль користувачів'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='D:\\Metrics\\GenealogyBoutiqueTree\\backend\\media/userprofile/photos/default.jpg', null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000239AE83FF40>/'),
        ),
    ]
