# Generated by Django 4.1.2 on 2022-12-11 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealWithClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique",
                    models.UUIDField(
                        auto_created=uuid.UUID("a92cd0c9-794c-11ed-9a40-2c3b706d7921"),
                        default=uuid.UUID("a92cd0c8-794c-11ed-9e50-2c3b706d7921"),
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001C9A8A4D4D0>/",
                    ),
                ),
                ("context", models.TextField(null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("genealog", models.CharField(max_length=255, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Угоди",
                "verbose_name_plural": "Угоди",
                "ordering": ["id"],
            },
        ),
    ]
