# Generated by Django 4.1.2 on 2022-10-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0009_alter_userprofile_options_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealWithClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('document', models.ImageField(upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002BF3AA1B580>/')),
                ('context', models.TextField(default=None)),
                ('is_published', models.BooleanField(default=False)),
                ('genealog', models.TextField(max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Сделки',
                'verbose_name_plural': 'Сделки',
                'ordering': ['id'],
            },
        ),
    ]
