# Generated by Django 4.1.2 on 2022-12-11 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_alter_dealwithclient_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealwithclient",
            name="document",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000027A00884C90>/",
            ),
        ),
        migrations.AlterField(
            model_name="dealwithclient",
            name="unique",
            field=models.UUIDField(
                auto_created=uuid.UUID("e8614aa6-794e-11ed-bfdb-2c3b706d7921"),
                default=uuid.UUID("e8614aa5-794e-11ed-873f-2c3b706d7921"),
            ),
        ),
    ]
