# Generated by Django 4.1.2 on 2022-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000258CA5AB580>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='genealog',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
