# Generated by Django 4.1.2 on 2022-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_alter_dealwithclient_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000210B0C6B580>/'),
        ),
    ]
