# Generated by Django 4.1.2 on 2022-10-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_userprofile_avatar_alter_userprofile_user'),
        ('deal', '0005_alter_dealwithclient_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001871933B580>/'),
        ),
    ]
