# Generated by Django 4.1.2 on 2022-10-22 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_alter_dealwithclient_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(default=uuid.UUID('6fefc62d-5220-11ed-afdb-3ca0670bcd37')),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002A64D43B580>/'),
        ),
    ]
