# Generated by Django 4.1.2 on 2022-10-25 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_alter_userprofile_avatar'),
        ('deal', '0007_dealwithclient_unique_alter_dealwithclient_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000271CB5FB580>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('c5f307b4-545c-11ed-aafe-2c4d54929b0f'), default=uuid.UUID('c5f307b3-545c-11ed-83e0-2c4d54929b0f')),
        ),
    ]
