# Generated by Django 4.1.2 on 2022-10-25 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_alter_dealwithclient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000023D83D0B580>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('46f0d719-545d-11ed-bbbd-2c4d54929b0f'), default=uuid.UUID('46f0d718-545d-11ed-a361-2c4d54929b0f')),
        ),
    ]
