# Generated by Django 4.1.2 on 2022-10-25 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001FDFD2CB580>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('7dc9b521-545d-11ed-b8c8-2c4d54929b0f'), default=uuid.UUID('7dc9b520-545d-11ed-862e-2c4d54929b0f')),
        ),
    ]
