# Generated by Django 4.1.2 on 2022-10-25 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0011_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000021B515AB580>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('e5b63cab-546a-11ed-b665-2c4d54929b0f'), default=uuid.UUID('e5b63caa-546a-11ed-8049-2c4d54929b0f')),
        ),
    ]
