# Generated by Django 4.1.2 on 2022-10-25 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0012_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001E45F131C60>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('6bab56eb-546f-11ed-898b-2c4d54929b0f'), default=uuid.UUID('6bab56ea-546f-11ed-bddd-2c4d54929b0f')),
        ),
    ]
