# Generated by Django 4.1.2 on 2022-10-26 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0014_alter_dealwithclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x00000202B9B34190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('2d4f8e2e-5549-11ed-8457-2c4d54929b0f'), default=uuid.UUID('2d4f8e2d-5549-11ed-937f-2c4d54929b0f')),
        ),
    ]
