# Generated by Django 4.1.2 on 2022-10-27 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0016_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000020C6CCB4190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('4f5ecdfd-5610-11ed-bda4-3ca0670b2ec7'), default=uuid.UUID('4f5ecdfc-5610-11ed-bdce-3ca0670b2ec7')),
        ),
    ]
