# Generated by Django 4.1.2 on 2022-10-27 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0017_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000028CDD2F4190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('7992e71a-5610-11ed-88fd-3ca0670b2ec7'), default=uuid.UUID('7992e719-5610-11ed-a69e-3ca0670b2ec7')),
        ),
    ]
