# Generated by Django 4.1.2 on 2022-10-27 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0018_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001FA49DF4190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('b0b57b87-5610-11ed-979b-3ca0670b2ec7'), default=uuid.UUID('b0b57b86-5610-11ed-a5c1-3ca0670b2ec7')),
        ),
    ]
