# Generated by Django 4.1.2 on 2022-10-27 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0019_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001DB4E454190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('ff540cb1-5610-11ed-8135-3ca0670b2ec7'), default=uuid.UUID('ff540cb0-5610-11ed-95b9-3ca0670b2ec7')),
        ),
    ]
