# Generated by Django 4.1.2 on 2022-10-27 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0020_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002099A934190>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('1b97831e-5611-11ed-87db-3ca0670b2ec7'), default=uuid.UUID('1b97831d-5611-11ed-a4c9-3ca0670b2ec7')),
        ),
    ]
