# Generated by Django 4.1.2 on 2022-10-27 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0021_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000001BAF6EDF550>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('763c3612-5612-11ed-bebd-3ca0670b2ec7'), default=uuid.UUID('763c3611-5612-11ed-9d10-3ca0670b2ec7')),
        ),
    ]
