# Generated by Django 4.1.2 on 2022-10-27 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0022_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000023F0B50F550>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('87a80d9d-563c-11ed-9226-3ca0670b2ec7'), default=uuid.UUID('87a80d9c-563c-11ed-8188-3ca0670b2ec7')),
        ),
    ]
