# Generated by Django 4.1.2 on 2022-10-27 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0024_alter_dealwithclient_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealwithclient',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000013AF3ACF520>/'),
        ),
        migrations.AlterField(
            model_name='dealwithclient',
            name='unique',
            field=models.UUIDField(auto_created=uuid.UUID('a6a34e5e-563e-11ed-b004-3ca0670b2ec7'), default=uuid.UUID('a6a34e5d-563e-11ed-86e5-3ca0670b2ec7')),
        ),
    ]
